apiVersion: v1
kind: Service
metadata:
  name:nginxsvc
spec:
  type: NodePort  #With NodePort Service We can access Application Out of Cluster 
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
