Replication Controller
----------------------

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 1
  selector:
    app: nginx1
  template:  #Pod Template
    metadata:
      name: nginxpod
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginxcont
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  selector: 
    app: nginx1 
  ports:
  - port: 80
    targetPort: 80