apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: spring-pod
      labels:
        app: springapp
    spec:
      containers:
      - name: springcontainer
        image: prataptec22/spring-boot-mongo:1
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
        - name: MONGO_DB_HOSTNAME
          value: mongosvc        #mongodb service 
        - name: MONGO_DB_USERNAME
          value: admin
        - name: MONGO_DB_PASSWORD
          value: Admin@123
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongorc
spec:
  replicas: 1
  selector:
    app: mongoapp
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongoapp
    spec:
      containers:
        - name: mongocontainer
          image: mongo
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: Admin@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  selector:
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017



