Deployment RollingUpdate
------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdp
spec:
  replicas: 2
  revisionHistoryLimit: 10 # default is 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: nginx
  template: #Pod Template
      metadata:
        name: nginxpod
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: prataptec22/nginx:1
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80

       