apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginxhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginxdep
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
spec:
  selector:
    matchLabels:
      app: nginx
  template:  #Pod template
    metadata:
      name: nginxpod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx 
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80


        

